baseURL = "https://Kiet1502.github.io/fcj-workshop-template/"
relativeURLs = false
canonifyURLs = true
defaultContentLanguage = "en"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = "Personal AWS internship report site built with Hugo and the FCJ workshop template."
  author = "Vũ Gia Kiệt"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "AWS Internship Report Site"
weight = 1
label = "English"
[Languages.en.params]
  author = "Vu Gia Kiet"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Repository"
identifier = "GitHub Repository"
url = "https://github.com/Kiet1502/fcj-workshop-template"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> LinkedIn"
identifier = "LinkedIn Profile"
url = "https://www.linkedin.com/in/ki%E1%BB%87t-v%C5%A9-gia-694432403/"
weight = 30

[Languages.vi]
title = "Báo Cáo Thực Tập AWS - Vũ Gia Kiệt"
weight = 2
label = "Tiếng Việt"
[Languages.vi.params]
  author = "Vũ Gia Kiệt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Mã nguồn GitHub"
identifier = "GitHub Repository"
url = "https://github.com/Kiet1502/fcj-workshop-template"
weight = 10

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> LinkedIn"
identifier = "LinkedIn Profile"
url = "https://www.linkedin.com/in/ki%E1%BB%87t-v%C5%A9-gia-694432403/"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
